# blue.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=BLUE VERSION"
          ports:
            - containerPort: 5678
